### ISSUE TITLE
Node.js changed HTTP2 API

### ISSUE THREAD

**Issue by Addono** [RisingStack/http2-push-example#6]
I was getting the following error:
```
...\http2-push-example\src\server.js:28
    pushStream.respondWithFD(file.fileDescriptor, file.headers)
               ^

TypeError: Cannot read property 'respondWithFD' of null
    at stream.pushStream (...\http2-push-example\src\server.js:28:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

[Apparently](https://github.com/nodejs/node/issues/18490) the [HTTP2 API](https://github.com/nodejs/node/pull/17406#issuecomment-356661798) of Node was changed in 9.4.

**Comment by yddmgirl** [comment]
I have the same issue

**Comment by RamyAlshurafa** [comment]
see this #8

**Comment by NabiKAZ** [comment]
Need merge: https://github.com/RisingStack/http2-push-example/pull/7
